name: Build React Native Android (auto keystore)

on:
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        working-directory: .
        run: yarn install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # generate keystore file
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -storetype PKCS12 \
            -keystore app/release.keystore \
            -alias release-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass password123 \
            -keypass password123 \
            -dname "CN=GitHub CI,O=CI,C=US"

      # create keystore.properties using keys expected by your gradle file
      - name: Create keystore.properties
        run: |
          cat <<EOF > keystore.properties
          storeFile=release.keystore
          storePassword=password123
          keyAlias=release-key
          keyPassword=password123
          EOF

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/*.apk
